// THIS FILE IS AUTO-GENERATED BY PATCH. See prompt for details.
"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";

const HERO_MOCKUP_SRC = "/hero-mockup.png";

const primaryFeatures = [
  {
    title: "Inviti privati",
    text: "Condividi un link curato, approva richieste e tieni il controllo della lista senza passare da mille chat.",
  },
  {
    title: "Gestione smart",
    text: "Partecipanti, conferme, quote e presenza in un unico flusso mobile-first, pulito e immediato.",
  },
  {
    title: "Disposable gallery",
    text: "Le foto si sbloccano al momento giusto e trasformano il post-serata in parte dell’esperienza.",
  },
];

const useCases = [
  {
    title: "Per compleanni, house party e serate private",
    text: "Echo è pensata per eventi che devono restare controllati, curati e belli da condividere.",
  },
  {
    title: "Per chi vuole un invito che faccia già atmosfera",
    text: "Prima ancora che la festa inizi, l’esperienza ha già una forma più chiara e più memorabile.",
  },
  {
    title: "Per chi non vuole più organizzare tutto in chat",
    text: "Approva, aggiorna, conferma e gestisci tutto dall’app, con una UX più lineare e più elegante.",
  },
];

const testimonials = [
  {
    quote:
      "Finalmente un modo davvero ordinato e bello per organizzare una festa privata senza perdersi tra liste e messaggi.",
    name: "Marco R.",
    place: "Milano",
  },
  {
    quote:
      "La parte migliore è la gestione degli invitati: approvazioni, presenza e dettagli evento tutto nello stesso posto.",
    name: "Chiara T.",
    place: "Bologna",
  },
  {
    quote:
      "L’effetto disposable camera dà davvero personalità alla serata. Non sembra la solita app per eventi.",
    name: "Luca P.",
    place: "Roma",
  },
];

function Badge({ children }: { children: ReactNode }) {
  return (
    <div className="inline-flex items-center rounded-full border border-black/8 bg-white/72 px-4 py-1.5 text-sm text-black/50 shadow-[0_10px_24px_rgba(15,23,42,0.04)] backdrop-blur-xl">
      {children}
    </div>
  );
}

function TestimonialCard({ quote, name, place }: { quote: string; name: string; place: string }) {
  return (
    <div className="rounded-[30px] border border-black/8 bg-white/80 p-6 shadow-[0_12px_30px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(15,23,42,0.08)]">
      <p className="text-base leading-7 text-black/72">“{quote}”</p>
      <div className="mt-6 flex items-center gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-full bg-black text-sm font-semibold text-white">
          {name.charAt(0)}
        </div>
        <div>
          <div className="text-sm font-semibold text-black">{name}</div>
          <div className="text-sm text-black/40">{place}</div>
        </div>
      </div>
    </div>
  );
}

export default function Home() {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const onScroll = () => setScrollY(window.scrollY || 0);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const heroStyle = useMemo(() => {
    const limited = Math.min(scrollY, 900);
    return {
      mockup: {
        transform: `translate3d(${limited * -0.012}px, ${limited * 0.08}px, 0) rotate(${ -6 + limited * 0.003 }deg) scale(${1 + limited * 0.00005})`,
      },
      glowA: {
        transform: `translate3d(${-limited * 0.02}px, ${limited * 0.06}px, 0)`,
      },
      glowB: {
        transform: `translate3d(${limited * 0.025}px, ${limited * 0.08}px, 0)`,
      },
    };
  }, [scrollY]);

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#f4f5fb] text-black">
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute inset-0 bg-[linear-gradient(180deg,#f4f5fb_0%,#f7f0ff_38%,#edf5ff_100%)]" />
        <div className="absolute left-[-100px] top-[80px] h-[360px] w-[360px] rounded-full bg-[#b8d4ff]/42 blur-[120px]" />
        <div className="absolute right-[-80px] top-[160px] h-[380px] w-[380px] rounded-full bg-[#e8b8ff]/34 blur-[130px]" />
        <div className="absolute left-[15%] top-[560px] h-[280px] w-[280px] rounded-full bg-[#b8ffe2]/20 blur-[110px]" />
        <div className="absolute right-[12%] top-[520px] h-[260px] w-[260px] rounded-full bg-[#ffd7a8]/22 blur-[110px]" />
      </div>

      <main className="relative mx-auto flex w-full max-w-[1400px] flex-col px-6 pb-24 pt-6 sm:px-8 xl:px-12">
        <header className="sticky top-4 z-40 flex items-center justify-between rounded-full border border-black/8 bg-white/70 px-4 py-3 shadow-[0_8px_28px_rgba(15,23,42,0.05)] backdrop-blur-xl">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-black text-sm font-semibold text-white">
              e
            </div>
            <span className="text-sm font-medium text-black/72">echo</span>
          </div>

          <nav className="hidden items-center gap-8 text-sm text-black/45 lg:flex">
            <a href="#features" className="transition hover:text-black/85">
              Features
            </a>
            <a href="#use-cases" className="transition hover:text-black/85">
              Use cases
            </a>
            <a href="#testimonials" className="transition hover:text-black/85">
              Testimonials
            </a>
          </nav>

          <a
            href="/get"
            className="inline-flex h-11 items-center justify-center rounded-full bg-black px-5 text-sm font-semibold text-white transition duration-300 hover:-translate-y-0.5 hover:bg-black/90"
          >
            Scarica echo
          </a>
        </header>

        <section className="relative grid min-h-[88vh] items-center gap-16 py-14 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] lg:gap-10 lg:py-20">
          <div className="relative z-20 max-w-2xl">
            <Badge>Per eventi privati che lasciano l’echo</Badge>

            <h1 className="mt-7 max-w-5xl text-5xl font-semibold leading-[0.92] tracking-[-0.09em] text-black sm:text-7xl xl:text-[108px]">
              Organizza la festa con un’app che sembra già parte della serata.
            </h1>

            <p className="mt-6 max-w-xl text-base leading-8 text-black/52 sm:text-lg">
              Echo rende inviti, approvazioni, gestione invitati e disposable gallery un’unica esperienza più bella, più chiara e più memorabile.
            </p>

            <div className="mt-10 flex flex-col gap-4 sm:flex-row">
              <a
                className="inline-flex h-12 items-center justify-center rounded-full bg-black px-6 text-sm font-semibold text-white transition duration-300 hover:-translate-y-0.5 hover:bg-black/90"
                href="/get"
              >
                Scarica l’app
              </a>
              <a
                className="inline-flex h-12 items-center justify-center rounded-full border border-black/10 bg-white/78 px-6 text-sm font-semibold text-black transition duration-300 hover:-translate-y-0.5 hover:bg-white/90"
                href="#features"
              >
                Scopri di più
              </a>
            </div>

            <div className="mt-10 grid gap-3 sm:grid-cols-3">
              <div className="rounded-[26px] border border-black/8 bg-white/78 px-4 py-4 shadow-[0_12px_28px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_36px_rgba(15,23,42,0.08)]">
                <div className="text-[11px] uppercase tracking-[0.18em] text-black/35">Inviti</div>
                <div className="mt-2 text-lg font-semibold text-black">Privati</div>
              </div>
              <div className="rounded-[26px] border border-black/8 bg-white/78 px-4 py-4 shadow-[0_12px_28px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_36px_rgba(15,23,42,0.08)]">
                <div className="text-[11px] uppercase tracking-[0.18em] text-black/35">Gestione</div>
                <div className="mt-2 text-lg font-semibold text-black">Smart</div>
              </div>
              <div className="rounded-[26px] border border-black/8 bg-white/78 px-4 py-4 shadow-[0_12px_28px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_36px_rgba(15,23,42,0.08)]">
                <div className="text-[11px] uppercase tracking-[0.18em] text-black/35">Foto</div>
                <div className="mt-2 text-lg font-semibold text-black">Disposable</div>
              </div>
            </div>
          </div>

          <div className="relative flex items-center justify-center lg:justify-end">
            <div
              className="absolute left-[4%] top-[10%] h-[260px] w-[260px] rounded-full bg-[#cfe4ff]/55 blur-[100px]"
              style={heroStyle.glowA}
            />
            <div
              className="absolute right-[4%] top-[16%] h-[300px] w-[300px] rounded-full bg-[#ffd6ef]/45 blur-[120px]"
              style={heroStyle.glowB}
            />

            <div className="relative w-full max-w-[980px]">
              <div className="rounded-[40px] border border-black/8 bg-white/52 p-4 shadow-[0_30px_90px_rgba(15,23,42,0.08)] backdrop-blur-2xl">
                <div className="rounded-[30px] border border-black/8 bg-[linear-gradient(180deg,rgba(255,255,255,0.72),rgba(255,255,255,0.58))] p-4 sm:p-6">
                  <img
                    src={HERO_MOCKUP_SRC}
                    alt="Echo app preview"
                    style={heroStyle.mockup}
                    className="mx-auto h-auto w-full object-contain drop-shadow-[0_40px_90px_rgba(15,23,42,0.16)] transition duration-500 hover:-translate-y-1"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="features" className="border-t border-black/8 py-16 sm:py-20">
          <div className="grid gap-10 lg:grid-cols-[minmax(0,0.7fr)_minmax(0,1.3fr)] lg:items-start">
            <div className="max-w-lg">
              <Badge>Features</Badge>
              <h2 className="mt-5 text-3xl font-semibold tracking-tight text-black sm:text-5xl">
                Tutto quello che serve per organizzare un evento privato, in un unico posto.
              </h2>
            </div>

            <div className="grid gap-4 md:grid-cols-3">
              {primaryFeatures.map((feature, index) => {
                const accents = ["#ff84c1", "#7dbfff", "#ffd36a"];
                return (
                  <div
                    key={feature.title}
                    className="rounded-[32px] border border-black/8 bg-white/80 p-6 shadow-[0_12px_30px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(15,23,42,0.08)]"
                  >
                    <div className="flex items-center gap-2">
                      <div className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: accents[index] ?? accents[0] }} />
                      <div className="text-[11px] uppercase tracking-[0.18em] text-black/35">echo</div>
                    </div>
                    <h3 className="mt-4 text-2xl font-semibold leading-tight tracking-tight text-black">{feature.title}</h3>
                    <p className="mt-4 text-sm leading-7 text-black/50">{feature.text}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        <section id="use-cases" className="border-t border-black/8 py-16 sm:py-20">
          <div className="max-w-2xl">
            <Badge>Use cases</Badge>
            <h2 className="mt-5 text-3xl font-semibold tracking-tight text-black sm:text-5xl">
              Pensata per chi vuole feste private meglio organizzate e più belle da vivere.
            </h2>
          </div>

          <div className="mt-10 grid gap-4 lg:grid-cols-3">
            {useCases.map((item, index) => {
              const gradients = [
                "from-[#ffd9ef]/65",
                "from-[#dcecff]/75",
                "from-[#fff0c8]/75",
              ];
              return (
                <div
                  key={item.title}
                  className="relative overflow-hidden rounded-[34px] border border-black/8 bg-white/80 p-6 shadow-[0_12px_30px_rgba(15,23,42,0.05)] backdrop-blur-xl transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_42px_rgba(15,23,42,0.08)]"
                >
                  <div className={`absolute inset-x-0 top-0 h-24 bg-gradient-to-b ${gradients[index] ?? gradients[0]} to-transparent`} />
                  <div className="relative z-10">
                    <div className="h-2.5 w-2.5 rounded-full bg-black/70" />
                    <h3 className="mt-4 text-2xl font-semibold tracking-tight text-black">{item.title}</h3>
                    <p className="mt-4 text-sm leading-7 text-black/50">{item.text}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        <section id="testimonials" className="border-t border-black/8 py-16 sm:py-20">
          <div className="grid gap-10 lg:grid-cols-[minmax(0,0.7fr)_minmax(0,1.3fr)] lg:items-start">
            <div className="max-w-lg">
              <Badge>Testimonials</Badge>
              <h2 className="mt-5 text-3xl font-semibold tracking-tight text-black sm:text-5xl">
                L’esperienza deve convincere prima ancora della festa.
              </h2>
            </div>

            <div className="grid gap-4 md:grid-cols-3">
              {testimonials.map((review) => (
                <TestimonialCard key={`${review.name}-${review.place}`} {...review} />
              ))}
            </div>
          </div>
        </section>

        <section className="border-t border-black/8 py-16 sm:py-20">
          <div className="rounded-[40px] border border-black/8 bg-white/78 px-6 py-10 text-center shadow-[0_12px_34px_rgba(15,23,42,0.05)] backdrop-blur-xl sm:px-10 sm:py-14">
            <Badge>Download echo</Badge>
            <h2 className="mx-auto mt-6 max-w-4xl text-3xl font-semibold tracking-tight text-black sm:text-5xl">
              La prossima festa che organizzi può sembrare già un ricordo prima ancora di iniziare.
            </h2>
            <p className="mx-auto mt-5 max-w-2xl text-base leading-8 text-black/50">
              Scarica echo e trasforma inviti, gestione e gallery in un’esperienza più curata, più condivisibile e molto più memorabile.
            </p>
            <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <a
                href="/get"
                className="inline-flex h-12 items-center justify-center rounded-full bg-black px-6 text-sm font-semibold text-white transition duration-300 hover:-translate-y-0.5 hover:bg-black/90"
              >
                Scarica l’app
              </a>
              <a
                href="#features"
                className="inline-flex h-12 items-center justify-center rounded-full border border-black/10 bg-white/78 px-6 text-sm font-semibold text-black transition duration-300 hover:-translate-y-0.5 hover:bg-white/90"
              >
                Esplora le feature
              </a>
            </div>
          </div>
        </section>

        <footer className="flex flex-col items-center justify-between gap-4 border-t border-black/8 py-8 text-sm text-black/35 sm:flex-row">
          <div>© 2026 echo. All rights reserved.</div>
          <div className="flex items-center gap-6">
            <a href="/privacy" className="transition hover:text-black/70">
              Privacy
            </a>
            <a href="/get" className="transition hover:text-black/70">
              Scarica echo
            </a>
          </div>
        </footer>
      </main>
    </div>
  );
}
